# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f906bdfb8d348d5457e34f2464daa38d7072fb6ae6a20a92e6c54a21cc58303479639a33102e9bce04f53d0c919a961ded4cab6a605f557699e2aea62d1daa6

test:
  secret_key_base: 0e7375f37ca8082cc9034fc88b5e22cbfa510453817c6c9b0dcf11746dbf34ce418dad9ae95da19550f9f32169aff86ed9dbdebb254b389d98f950cee5ee1e60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
